### ISSUE TITLE
Use user-setting line endings

### ISSUE THREAD

**Issue by tunght13488** [morganestes/sublime-recess#5]
On Windows 7, I notices that compiled CSS files' **use Unix line endings**, although my user-setting specified that I **use "System" line endings**.

I don't know this is a bug or new feature?

**Comment by morganestes** [comment]
I can check on it. Where did you specify your line endings (which file)? That'll help me know where to start.

Also, what are you using to check your line endings?

**Comment by morganestes** [comment]
@tunght13488 It looks like this is coming directly from Recess, not from this plugin. See https://github.com/twitter/recess/blob/master/lib/core.js#L158 and https://github.com/twitter/recess/blob/master/lib/core.js#L171 for the relevant code.

**Comment by tunght13488** [comment]
@morganestes My user-setting line ending is in `Packages/User/Preferences.sublime-settings`: `"default_line_ending": "windows"`.  
I think you're right. This is from Recess, not the plugin.
